### ISSUE TITLE
Add option for landscape level to have "left" and "right" displayed

### ISSUE THREAD

**Issue by TacoTheDank** [woheller69/Level#10]
When attempting to level something like a picture frame on a wall, I think it would help to know which way the frame is slightly tilted if I'm trying to be super precise. Perhaps this could be more of an accessibility thing as well for those who may have visual disabilities and find the bubble itself hard to read when it already looks centered.

As an example, if something is tilted 01.5 degrees to the left, there could be an arrow pointing to the left just above the degree display, and vice versa for a right tilt.

This should be an option though, as not everyone may like it or have a use for it.

**Comment by woheller69** [comment]
I don't like to add new elements in this old app. The screen is manually painted with stuff like doDraw(Canvas canvas)...
But I think, I could add an arrow like I added the degree sign ° to the number. The arrow could point towards the direction you need to turn in order to level
Or I might change the color for positive and negative angles, e.g green and red.

**Comment by woheller69** [comment]
What about this? Rename to .apk before installing.
[app-release.apk.zip](https://github.com/woheller69/Level/files/7533447/app-release.apk.zip)

**Comment by woheller69** [comment]
![Screenshot_Bubble](https://user-images.githubusercontent.com/68678880/141740684-fed91c6a-cd9d-4538-b628-a9e314a149a5.png)

**Comment by TacoTheDank** [comment]
@woheller69 It looks good! I really like that implementation. Thank you :) Will you add it as is, or will you make it a setting? (I don't really mind either way)

**Comment by woheller69** [comment]
New version released. Should be through F-Droid in a few days.
The arrows will always be there, no extra setting
