### ISSUE TITLE
Angle as slope

### ISSUE THREAD

**Issue by ElDespacito** [woheller69/Level#13]
When setting the angle as slope (%) the value is counting up until Infinity.

**Comment by woheller69** [comment]
That depends on how you hold the phone. If you lock the orientation and hold it up infinity is correct

**Comment by ElDespacito** [comment]
I missed to understand your answer. When I don't move my phone, the value
is counting up until Infinity. This in any position of the phone, locked or
unlocked.

woheller69 ***@***.***> schrieb am Mo., 13. Dez. 2021, 18:33:

**Comment by woheller69** [comment]
I do not see why this goes to infinity in the code (it is even limited to 999.9). But the good thing is that I detected an error in the calculation of inclination which has been around since 2013...
