### ISSUE TITLE
full screen mode

### ISSUE THREAD

**Issue by shockergit** [woheller69/Level#17]
please add full screen mode for app without navigation button and status bar.

**Comment by woheller69** [comment]
why do you need that?

**Comment by woheller69** [comment]
Ok, for the ruler full screen is better.
I made it almost full screen.

Please try:
-Uninstall
-Remove .zip and install

[app-release.apk.zip](https://github.com/woheller69/Level/files/12147048/app-release.apk.zip)

**Comment by woheller69** [comment]
In this version the "almost" full screen mode is only used if the ruler is shown.
Otherwise it might be difficult for some users to find the navigation buttons to close the app.

[app-release.apk.zip](https://github.com/woheller69/Level/files/12157823/app-release.apk.zip)

**Comment by shockergit** [comment]
> In this version the "almost" full screen mode is only used if the ruler is shown. Otherwise it might be difficult for some users to find the navigation buttons to close the app.
> 
> [app-release.apk.zip](https://github.com/woheller69/Level/files/12157823/app-release.apk.zip)

thank you soo much thats what i needed

**Comment by woheller69** [comment]
Added calibration for ruler

[app-release.apk.zip](https://github.com/woheller69/Level/files/12169189/app-release.apk.zip)
