### ISSUE TITLE
Calibration of the ruler

### ISSUE THREAD

**Issue by mmahmoudian** [woheller69/Level#18]
Thanks for creating and maintaining this app. It truly comes handy from time to time.

## Issue

Different phones have different screen sizes. On my current phone has "6.3inch Full HD+ display" according to the specs. I for the first time needed to use the ruler of this app, but the distances didn't look right. I managed to find a normal plastic ruler from the office supply and put it on my phone screen. Actual 10cm is as long as 7.9 units in the app.

## Suggestion
Considering that the ruler is dynamically generated, and considering that people don't change phones that often, it would be nice to have a way to calibrate the ruler we see on the screen using an actual real-world ruler.

I can think of one easy way to implement this. create a calibration mode (e.g accessible from the settings) that shows rulers (metric and imperial) as it normally shows, but it allows the user to either pinch zoom or normal scroll (because the 0 is fixed to the edge of the screen anyways) to adjust the scale. Then this scale is stored on the device and every time user load the ruler page, that scale is multiplied to the unit of distances that generates the rulers.

**Comment by woheller69** [comment]
I already implemented a calibration. It is already available on F-Droid

https://f-droid.org/repo/org.woheller69.level_24.apk

**Comment by mmahmoudian** [comment]
Thanks for the comment. I just updated and yes it is there (previously the same button showed calibration for bubble and was notifying me to put the phone on a flat surface). Thanks :)

But there is one and a half major issues:
1. the calibration icon looks a lot like the bubble UI. I understand that the ruler button is suppose to toggle between ruler and bubble, but the icon of the ruler does not change. So logically the user would think one button is for bubble and one for the ruler. Perhaps a better icon or moving it inside the settings can help with this confusion.
2. The range is not enough for my phone. I have decreased the size to the lowest possible and still physical 10cm or 8.1 units in the app. Would is be possible to increase the range (e.g double)?

**Comment by woheller69** [comment]
That is very strange. Usually the phones know the dpi value of their display.
On my devices the error is ~1mm / 1%

**Comment by woheller69** [comment]
what is your device / OS /Android version?

**Comment by mmahmoudian** [comment]
My phone is [FairPhone4](https://shop.fairphone.com/fairphone-4) with Android 12

**Comment by sphh** [comment]
I also cannot get the size of the ruler right:
- lowest setting: 4 units = 47mm
- highest setting: 4 units = ~48.8mm

My phone is a (tiny) Unihertz Jelly Pro with
- Width: 240 px (~30.5mm)
- Height: 432 px (~57.8mm)
- Dp Width: 320dp
- Dp Height: 576dp
- Density: 0.75
- Density class: ldpi

PS: I would also prefer, if the icon switching between level and ruler would adapt, e.g. showing a ruler, if in level mode and showing a level if in ruler mode. I can envisage, that the only difference between those two icons are:
- the ruler icon shows the graduation at the top (as it is at the moment)
- the level icon is also a rectangle but shows a bubble at the top

The calibration icon looks to me like a target, so I find it obvious. Personally I believe, there is no need for an icon at all: I would expect to find it in the ⋮ menu, because it is not needed on a daily basis …

**Comment by woheller69** [comment]
Very strange, to me these seem to be bugs on your devices.
Can you try this version and make a screenshot of the toast being shown when the ruler is shown? 
This shows the 
- number of pixels/mm of the device (height direction)
- the height of the window showing the ruler in pixels
- the calculated height of the window in mm

Uninstall
Remove .zip and install
[app-release.apk.zip](https://github.com/woheller69/Level/files/12261907/app-release.apk.zip)

**Comment by sphh** [comment]
Here is the screenshot for the Unihertz Jelly Pro:
![Screenshot_20230804-170738](https://github.com/woheller69/Level/assets/4856462/216969e7-11cf-4a94-8fb4-aa0c8571df05)

**Comment by woheller69** [comment]
Obviously your displayMetrics has a wrong dpi value for your device.
432 real pixels and 57.8 mm should give 7.47 dpmm but the screenshot says 9.45 dpmm

**Comment by sphh** [comment]
Oh, well, not much I can do about it, is there? Could it have to do with the `density`, because 9.45/7.47 = 0.79, which is close to the density setting of 0.75? Just a (probably ignorant) idea …

**Comment by woheller69** [comment]
maybe. But I have devices with density of 1.5 , 2 , 3.15, ... and they all work almost without calibration. Maybe 0.5mm wrong on a 10cm scale...

**Comment by atom-smasher** [comment]
I just updated via F-Droid. Running RR, Android-10, on a Moto G8 Power. With the ruler calibration slider all the way up, the ruler scale is still about 20% too big.

**Comment by woheller69** [comment]
I am not so happy about having to fix bugs in the OS on some devices...
But please try if that version gives enough range and let me know the CAL value from the toast when you finish 
calibration by pressing the calibration button again.

Uninstall
Remove .zip and install

[app-release.apk.zip](https://github.com/woheller69/Level/files/12267121/app-release.apk.zip)

**Comment by mmahmoudian** [comment]
@woheller69 I believe all this can be avoided and fixed if the slider range goes twice as much as it goes now. This way even if the OS is buggy, the user still get to choose the appropriate scaling ratio

**Comment by woheller69** [comment]
But it is much harder to calibrate accurately if the range is that large

**Comment by sphh** [comment]
One way around this would be either two sliders (one for the coarse setting and one for the fine). Another to but a button on either end of the slider which does the coarse calibration and the slider is responsible for the fine tuning. This can be combined into one slider with progressive (exponential?) sensitivity, that is the further away from the zero it is, the larger the adjustment is. If you lift your finger from the slider, it will ‘reset’ itself, that is, the current adjustment becomes the new zero. In all cases the calibration becomes a two step process: Firstly adjust the size roughly and then do the fine tuning. A `Reset` button might help if you get lost. But are is just some ideas how to handle this awkward situation without loosing the accuracy of the calibration process …

**Comment by woheller69** [comment]
Please try the apk and let me know the required calibration values. Then we will see...

[app-release.apk.zip](https://github.com/woheller69/Level/files/12267518/app-release.apk.zip)

**Comment by sphh** [comment]
I tried it, but the lowest setting of the slider still gives a unit which is too large. Looks to me, that the no correction setting of the slider is not at the centre of the slider.

PS: I like the new switching icon! Why is there no setting menu in the ruler mode?

**Comment by woheller69** [comment]
Please try this. This provides a coarse calibration and a fine calibration
[app-release.apk.zip](https://github.com/woheller69/Level/files/12268210/app-release.apk.zip)

No settings in ruler mode because the other settings are only for spirit level feature.

**Comment by sphh** [comment]
That works. I get `Fine: 142 Coarse 3164`.

May I suggest to put labels on the sliders? (And maybe the units `cm` and `in` on the left and right ruler?)

I see, why you don't put the settings icon into the ruler mode. Personally I prefer, that the icons would not change position when switching modi. But I guess that is down to personal preferences.

**Comment by woheller69** [comment]
I don't like labels as they always need translations...
So, if possible, I avoid them.

**Comment by woheller69** [comment]
I modified the sliders. The icons depict "coarse" and "fine" calibration now.

Please all let me know your required calibration values. 
Once this new calibration is published and your device is still out of range I will not change it anymore...

[app-release.apk.zip](https://github.com/woheller69/Level/files/12269911/app-release.apk.zip)

**Comment by sphh** [comment]
Perfect! Thanks for going that extra mile.

**Comment by woheller69** [comment]
@mmahmoudian @atom-smasher can you please also try and tell me the calibration values?
