### ISSUE TITLE
add movable markers to ruler

### ISSUE THREAD

**Issue by ulrich-mayer** [woheller69/Level#21]
Two ideas to improve usability:

1. Add markers to ruler. E.g. one to move 0 and an additional one at any point, to more easily measure.  2nd one ideally with similar ways to move fast and slow as with the calibration.

2. Add config option to start app with ruler

**Comment by woheller69** [comment]
Just move your object to "0" and read the value at the other end of the object

**Comment by ulrich-mayer** [comment]
I understand that.
I have used "Lineal, Ruler" by "Nixgame" 
https://nixgame-ruler.de.aptoide.com/app
and learned to appreciate this feature.
That's why I proposed the idea
