### ISSUE TITLE
Strings for Turkish Translation

### ISSUE THREAD

**Issue by SirCrownguard** [woheller69/Level#24]
Sorry. I had a problem with my computer and couldn't help you for a long time. Now I'm here, I'll translate the remaining strings.

[strings.txt](https://github.com/woheller69/Level/files/13054127/strings.txt)
[full_description.txt](https://github.com/woheller69/Level/files/13054157/full_description.txt)
[short_description.txt](https://github.com/woheller69/Level/files/13054159/short_description.txt)

**Comment by woheller69** [comment]
Thanks. For full_description you uploaded the wrong file. It is the same as strings.txt

**Comment by SirCrownguard** [comment]
My apologies! Here is it.
[full_description.txt](https://github.com/woheller69/Level/files/13186098/full_description.txt)

**Comment by SirCrownguard** [comment]
[full_description (1).txt](https://github.com/woheller69/Level/files/13186110/full_description.1.txt)
