### ISSUE TITLE
Add a way to see the version number in-app

### ISSUE THREAD

**Issue by JohnVeness** [woheller69/Level#26]
It would be useful if the version number of the app could be shown in the app, e.g. somewhere in the ... menu. I can find out the version number from e.g. F-Droid, but that's a bit more work! Thanks for this app.

**Comment by woheller69** [comment]
You can find the installed version from Android -> Settings -> Apps -> Bubble
At the bottom you see the version you currently use.
I don't think this needs to be displayed in app
