### ISSUE TITLE
Add .apk to the releases so it can be pulled into Obtanium

### ISSUE THREAD

**Issue by ironman92710** [woheller69/Level#29]
Please add the actual app .apk to the releases. This allows apps like Obtanium to detect the source and install and keep it updated without fdroid.

**Comment by woheller69** [comment]
Nope. Obtanium can also get releases from F-Droid

**Comment by ironman92710** [comment]
I have added it in this way, but I prefer if I have the APK come from your Github where the source code is hosted without having to rely on Fdroid at all. Thanks for replying and consider it in the future. As I understand this isn't too hard to do.

**Comment by ironman92710** [comment]
> Nope. Obtanium can also get releases from F-Droid

Is there a reason you are against it? I have added it in this way, but I prefer if I have the APK come from your Github where the source code is hosted without having to rely on Fdroid at all. Thanks for replying and consider it in the future. As I understand this isn't too hard to do.
