### ISSUE TITLE
Seperate calibration reset 

### ISSUE THREAD

**Issue by shockergit** [woheller69/Level#32]
please add seperate calibration reset for water level and ruler

**Comment by woheller69** [comment]
The ruler is not related to the reset of the water level

**Comment by shockergit** [comment]
![Screenshot_20240501_161325_Bubble](https://github.com/woheller69/Level/assets/63154802/e97fd065-27d7-4a98-a91e-013462af2d21)
![Screenshot_20240501_161307_Bubble](https://github.com/woheller69/Level/assets/63154802/d36397bd-a5ec-47b2-b774-d03bd00251bc)
no option to reset seperately in ruler

**Comment by woheller69** [comment]
Yes, just calibrate it again

**Comment by woheller69** [comment]
Added in V2.9

**Comment by shockergit** [comment]
ok
