### ISSUE TITLE
Per-app language preferences 

### ISSUE THREAD

**Issue by yurtpage** [woheller69/Level#34]
I updated the app from F-Droid to the v2.9 (beta) and to my surprise the recently added ru locale doesn't work.
For all other apps everything is fine, so something is missing.
The app doesn't have a built-n language chooser and as far I understood in order to change the localy externally the app should make some adjustments: 
https://developer.android.com/guide/topics/resources/app-languages

Maybe you know what went wrong?

**Comment by woheller69** [comment]
this is because the Russian translation came AFTER V2.9 was published.
Will be in next version.

**Comment by woheller69** [comment]
translations have been done by various contributors, e.g. #33
