### ISSUE TITLE
SUGGESTION: Digit display very rapid, could be slowed down.

### ISSUE THREAD

**Issue by billthefarmer** [woheller69/Level#4]
The digit display updates so rapidly it makes it difficult to read. Suggest it be slowed with an averaging function similar to the bubble display.

**Comment by haarp** [comment]
I just installed the new version. Much better now, thanks! :)

**Comment by woheller69** [comment]
Did you compile it yourself? I did not yet make a release

**Comment by haarp** [comment]
Weird. I've had like 100 refreshes per second the other day. Now it's down to a more reasonable roughly 5/s.

I thought installing v1.2 was the reason, but it turn out even v1.0 has the lower refresh rate. Maybe my device decided to provide sensor data more slowly all of a sudden?

**Comment by billthefarmer** [comment]
It's just the usual F-Droid sausage machine...
@woheller69 made a [release](https://github.com/woheller69/Level/releases/tag/V1.2) on 26 Oct
F-Droid [checkupdates](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.woheller69.level.yml) picked it up on the 27th
F-Droid [built](https://f-droid.org/wiki/page/org.woheller69.level/lastbuild_12) it on the 28th &ndash; They've deprecated their wiki, but it still logs builds
And it got updated on my phone today.

**Comment by JohnVeness** [comment]
Has there been a regression? I haven't used older versions, but in version 2.6 (from F-Droid) the digits update too fast to read.

**Comment by woheller69** [comment]
I think it is just because our phones are getting faster.
Please try this version.
-Uninstall
-Remove .zip and install
[app-release.apk.zip](https://github.com/woheller69/Level/files/13952510/app-release.apk.zip)

I decoupled display speed from sensor speed. New values are only shown after at least 300ms.

**Comment by woheller69** [comment]
-> V2.7

**Comment by JohnVeness** [comment]
Thanks for the update. Are you able to do the same to the up/down arrow - when you are close to level it flickers very quickly, like the numbers used to.

https://github.com/woheller69/Level/assets/2512915/dba67720-3fd4-423d-b83e-6b22b114069c

**Comment by woheller69** [comment]
I don't think the arrows should be delayed. They show the direction you should move and vanish if you should stop. The arrow flickers between stop and move when you are very close
