### ISSUE TITLE
Related to Bubble Level on Google Play Store?

### ISSUE THREAD

**Issue by e-t-l** [woheller69/Level#6]
Hi, is this related to [this Bubble Level app](https://play.google.com/store/apps/details?id=net.androgames.level&hl=en_US&gl=US) on the Google Play Store, (which I believe used to be based on an open-source project)?

**Comment by e-t-l** [comment]
Nevermind, I just realized the answer must be yes, because the Play store version is at https://play.google.com/store/apps/details?id=**net.androgames.level**, while you mention in the ReadMe that this app is based off the Bubble Level app at https://f-droid.org/de/packages/**net.androgames.level**. The package names are the same.

**Comment by yashpalgoyal1304** [comment]
hi, thanks for opening this issue. i also had the same doubt (albeit i knew that app primarily from f-droid).

**Comment by yashpalgoyal1304** [comment]
so, 
* [woheller69] <-- [hakan42] <-- ... <-- [avianey]

[avianey]: https://github.com/avianey/Level
[hakan42]: https://github.com/hakan42/Level
[woheller69]: https://github.com/woheller69/Level
