### ISSUE TITLE
Suggestion: Calibration on unleveled surface

### ISSUE THREAD

**Issue by audthmbs** [woheller69/Level#7]
Upd: Just placed the figure inline (didn't find an "attach" button yesterday).

Hello, woheller69!

Is it possible to implement this feature on your application?
Take a look at the explaining figure

![bitmap_medium](https://user-images.githubusercontent.com/71224730/140603474-fc4b9c52-0a0c-432f-964f-ecf1e02e5a22.png)

Legend:
	blue -- phone with normal to it 
	red -- improper installed gravity sensor (with normal to it)
	dashed teal -- phone 180 degrees turned around
	dashed brown -- the very same gravity sensor 180 degrees turned around
	dotted black -- true level
	cyan -- error
	magenta -- first readings
	green -- second readings: a phone is 180 degrees turned around

Lets say we have some error we'd like to compensate: Err 
(imprecise or improper installed gravity sensor) 
If a phone is placed on any surface it gets R1 readings,
then we turn the phone around 180 degrees and it gets readings R2.
The value of Err then is half a sum of absolute values R1 and R2.
(if my reasoning is not mistaken).

What do you think?

**Comment by woheller69** [comment]
It is a good idea, but I don't think I want to spend the effort to implement it.
I mainly wanted to revive this useful app and update it for Android 11.
But maybe someone else wants to dive into this and make a pull request...

**Comment by audthmbs** [comment]
Thank you, woheller69, anyway!
I wish i were a programmer :-)
Keep well and take care!

**Comment by woheller69** [comment]
I also think that factory calibration should usually be quite good. In my view the calibration feature can be used to measure angles relative to another surface

**Comment by elimuhub7407** [comment]
Calibration at an angle 45% - 100% @woheller69

**Comment by woheller69** [comment]
you mean an angle of 45°?
This equals 100%
